name: Demo
on: [push]
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: Checkout code from branch
        uses: actions/checkout@v3

      - name: List files in workspace
        run: |
          ls ${{ github.workspace }}

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Run Python
        run: |
          python --version

      # - name: Install Pytest
      #   run: |
      #     pip install pytest
    
      # - run: python pytest
      # Rather than installing each package needed for testing, you can create a requirements.txt file
      # and execute that in python with Github actions.

      # Another solution is to create a pipenv, generate a Pipfile, add pytest execution to '[scripts]'
      # in the pipfile. Execute the pytest variable in the Pipfile via Github actions

      - name: Install pipenv
        run: |
          pip install pipenv

      - name: Install dependencies
        run: |
          

      - name: Run pytest for boyer_moore
        run: |
          pytest